db:
  user: "user"
  pass: "pass"
  host: "db"
  port: "6534"
  dbName: "ScheduleDb"

bot:
  token: "6055714135:AAHJdRC6t6XWH1k-JI2ufXMlBHkL-9Q8L58"

endpoints:
  microservice: "http://default"
  frontend: "http://isuct-schedule.ru"
